Boltzmann interface dev
pecos/tps pull request #229
Opened 2023-09-06 17:11 UTC by uvilla

Developing the interface for the Boltzmann solver interface.

*Key changes*:
- Implemented a `Tps2Boltzmann` class (both c++ and python wrappers) to handle the sharing of information between the TPS and Boltzmann solver. A new section `[boltzmannInterface]` in the input file has been added to pass parameters to the interface.
- Added functionalities in `M2ulPhysS` to push thermodynamic state variables to `Tps2Boltzmann`.
- Modified `QuasiMagnetostaticSolver*` to optionally compute/store the electric field.
- Interpolate the electric field to the fluid mesh in `CycleAvgJouleCoupling`.
- Add a demo of the new interface (including a `BoltzmannMockSolver`) in `tps-time-loos.py`.
- Resolved many memory leaks in `QuasiMagnetostaticSolver*` and `M2ulPhysS`.

*Next milestones*:
- Create a `pytps` python package
- Improve the interface of `Tps2Boltzmann` to include variable name dictionaries and units
- Extend `Tps2Boltzmann` to handle GPU data directly. Dependents on #228 that allow EM solver to run on the build for GPUs
- Implement methods to read back Boltzmann fields in TPS

2023-09-08 22:07 UTC, uvilla commented
@trevilo :

There is a built in that fails in the `VPATH Testing` that I can not reproduce locally.
Other than that this first chuck is ready to be reviewed and merged.

Cheers,

Umberto

2023-09-08 22:17 UTC, trevilo commented
> @trevilo :
> 
> There is a built in that fails in the `VPATH Testing` that I can not reproduce locally. Other than that this first chuck is ready to be reviewed and merged.
> 
> Cheers,
> 
> Umberto

Thanks @uvilla.  The failing test is non-deterministic (by design unfortunately) so it fails occasionally.  I'd like to change that, but... that is a battle for another day.  I've triggered it to run again, and I'm guessing it will pass, especially since you couldn't reproduce locally.  If it passes, I'll look this over and get it merged asap.  If not, I'll take a closer look.

2023-09-11 16:23 UTC, trevilo requested changes
Hey @uvilla, just two tiny comments/questions.  After that, this looks ready to me.

2023-09-11 18:55 UTC, uvilla commented on src/M2ulPhyS2Bolzmann.cpp
> +// -----------------------------------------------------------------------------------bl-
File has been renamed as suggested.

2023-09-11 18:56 UTC, uvilla commented on src/cycle_avg_joule_coupling.cpp
> +  std::cout << "Nothing to be fetched in CycleAvgJouleCoupling" << std::endl;
Statement has been removed. Thank you for catching that.

2023-09-11 19:01 UTC, trevilo commented on src/M2ulPhyS2Bolzmann.cpp
> +// -----------------------------------------------------------------------------------bl-
Doh! I messed up and inadvertently took out the `2`, but what I was trying to point out is that `Bolzmann` should be `Boltzmann`.

2023-09-11 19:16 UTC, trevilo approved these changes

2023-09-12 01:48 UTC, merged